# switch out data
#
#
question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {
        "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

question_data2 = [{"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                  "question": "The Neanderthals were a direct ancestor of modern humans.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                  "question": "The first computer bug was formed by faulty wires.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                                  "question": "The first Maxis game to feature the fictional language &quot;Simlish&quot; was The Sims (2000).",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                  "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                  "difficulty": "medium",
                                  "question": "The anime Attack on Titan was directed by Tetsur\u014d Araki, the same person who directed the anime Highschool of the Dead.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                                  "question": "In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                                  "question": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                                  "question": "Arriva is owned by the Deutsche Bahn.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                                  "question": "In &quot;Star Trek&quot;, Klingons are commonly referred to as &quot;Black Elves&quot;.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                                  "question": "&quot;Neutral Milk Hotel&quot; is a real band.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]}]
